### ISSUE TITLE
More scope for optimisation

### ISSUE THREAD

**Issue by Liftoff-Studios** [ajeethbt/Rust-Multiplication#1]
Hey ajeeth this could be for optimised using for loop

```
use std::io;

fn main() {
    let mut num1: String = String::new();
    let mut num2: String = String::new();
    let mut result:i32 = 0;

    io::stdin().read_line(&mut num1).expect("Error my friend");
    io::stdin().read_line(&mut num2).expect("Error my friend");

    let num1 = num1.trim().parse::<i32>().expect("msg");
    let num2 = num2.trim().parse::<i32>().expect("msg");


    for _i in 0..num1{
        result = result + num2;
        
    }

    println!("Final Answer is: {}",result );
    
}
```

**Comment by puffinism** [comment]
> Hey ajeeth this could be for optimised using for loop
> 
> ```
> use std::io;
> 
> fn main() {
>     let mut num1: String = String::new();
>     let mut num2: String = String::new();
>     let mut result:i32 = 0;
> 
>     io::stdin().read_line(&mut num1).expect("Error my friend");
>     io::stdin().read_line(&mut num2).expect("Error my friend");
> 
>     let num1 = num1.trim().parse::<i32>().expect("msg");
>     let num2 = num2.trim().parse::<i32>().expect("msg");
> 
> 
>     for _i in 0..num1{
>         result = result + num2;
>         
>     }
> 
>     println!("Final Answer is: {}",result );
>     
> }
> ```

ah.. yeah for my calculator it is optimized thanks though

**Comment by ajeethbt** [comment]
Also this is my calculator code
`use std::io::stdin;

// will try and use pancurse and getch to make it look authentic


fn main() {
    let mut num1 = String::new();
    let mut oper = String::new();
    let mut num2 = String::new();

    println!("\n \n Please enter your first number");
    stdin().read_line(&mut num1).expect("Error");
    let num1g:f32 = num1.trim().parse().expect("Error");
     
    println!("Please enter the operation you want to use (*,/,+,-)");
    stdin().read_line(&mut oper).expect("Error");
    //let operg:u32 = num1.trim().parse().expect("Error");
    
    println!("Please enter your second number");
    stdin().read_line(&mut num2).expect("Error");
    let num2g:f32 = num2.trim().parse().expect("Error");

    if oper.trim()=="+"
    {
        print!("Result is: ");
        print!("{}",num1g+num2g);
    }else if oper.trim()=="-" {
        print!("Result is: ");
        print!("{}",num1g-num2g);
    }else if oper.trim()=="/" {
        print!("Result is: ");
        print!("{}",num1g/num2g);
    }else if oper.trim()=="*"{
        print!("Result is: ");
        print!("{}",num1g*num2g);
    }else {
       println!("Dude give proper operators i am too dumb to understand complex stuff.")
             
    }

    println!("\nMade by Ajeeth BT\n \n \nCode is not yet optimised will be updating it and will use getch and pancurse in upcoming updates, also will try to make it one line and reduce pressing enter.\n \n");


}
`

**Comment by puffinism** [comment]
I am still learning the pancurse crate once that is done ill update the code.

**Comment by puffinism** [comment]
Thanks! I'll do that way.

**Comment by Liftoff-Studios** [comment]
The reason i said it wasn't optimised was wgile loops take more space and event then for loops

**Comment by puffinism** [comment]
> The reason i said it wasn't optimised was wgile loops take more space and event then for loops

ah.. so you mean while loops take more space like in the sense ram? sure in that case ill use for loops

**Comment by Liftoff-Studios** [comment]
By energy i meant space
Usually while loops are more error prone and less concise.

They take up more Ram Diane add they use more variables

**Comment by Liftoff-Studios** [comment]
Autotype causing problems lol
I meant *and not*Diane

**Comment by puffinism** [comment]
> Diane

Np ill limit using while loops then, will use them when required, thanks! 

Edit: (Ill also update the code with for loops later)

**Comment by Liftoff-Studios** [comment]
Ok then. Great

**Comment by Liftoff-Studios** [comment]
Although what does the pancurse create do

**Comment by puffinism** [comment]
> Although what does the pancurse create do

pancurse is just a crate that allows better interaction between the os or the terminal, I am learning that for the calculator update which will allow for complete line reading and understanding without the need of pressing enter and also differentiate between numbers and characters and also allow multiple term calculation.

**Comment by puffinism** [comment]
So that you know you dont have to press enter everytime you want to give an input since there is no command called `stdin().read(&mut xyz)` and is `stdin().read_line(&mut xyz)` like in `print!("hello");` and `println!("hello");`
